import { Fredoka } from 'next/font/google';
import './globals.css';
import { AppContextProvider } from '@/app/contexts/AppContext';
import { PersonalizationProvider } from '@/app/contexts/PersonalizationContext';
import Navbar from '@/app/components/Navbar/Navbar';
import Footer from './components/Footer/Footer';

const fredoka = Fredoka({ subsets: ['latin'] });


export const metadata = {
  title: 'Kalu Cookies',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={fredoka.className}>
      
        <AppContextProvider>
        <PersonalizationProvider>
        
          <Navbar />
          {children}
          
        </PersonalizationProvider>
        </AppContextProvider>
       
        <Footer/>
      </body>
    </html>
  );
}
