import { Inter } from 'next/font/google';
import './globals.css';
//import localFont from '@next/font/local'

import { AppContextProvider } from '@/app/contexts/AppContext';
import Navbar from '@/app/components/Navbar/Navbar';
import Footer from './components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });
//const myFont = localFont({src: './Mungil-regular-ttf'})

export const metadata = {
  title: 'Kalu Cookies',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppContextProvider>
          <Navbar />
          {children}
        </AppContextProvider>
        <Footer/>
      </body>
    </html>
  );
}
